clients/urls.py
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('clients', views.client_list, name='client_list'),
    path('clients/<int:pk>/', views.client_detail, name='client_detail'),
    path('clients/new/', views.client_new, name='client_new'),
    path('clients/<int:pk>/edit/', views.client_edit, name='client_edit'),
    path('clients/<int:pk>/delete/', views.client_delete, name='client_delete'),
]

med/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from .models import Clients
from med.views import MedAutocomplete, ServiceAutocomplete

urlpatterns = [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    path('', views.med_list, name='med_list'),
    path('report', views.med_report, name='med_report'),
    path('med/new/', views.med_new, name='med_new'),
    path('med/<int:pk>/edit/', views.med_edit, name='med_edit'),
    path('med/<int:pk>/delete/', views.med_delete, name='med_delete'),
    url(r'^med-autocomplete/$', MedAutocomplete.as_view(), name='med-autocomplete'),
    url(r'^service-autocomplete/$', ServiceAutocomplete.as_view(), name='service-autocomplete'),
]

medecine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('med.urls')),
    path('', include('clients.urls')),
    path('', include('services.urls')),
]

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('services', views.service_list, name='service_list'),
    path('services/<int:pk>/', views.service_detail, name='service_detail'),
    path('services/new/', views.service_new, name='service_new'),
    path('services/<int:pk>/edit/', views.service_edit, name='service_edit'),
    path('services/<int:pk>/delete/', views.service_delete, name='service_delete'),
]

med/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from clients.models import Clients
from services.models import Services

class Med(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    client = models.ForeignKey(Clients, on_delete=models.CASCADE)
    service = models.ForeignKey(Services, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.text

med/forms.py
from dal import autocomplete
from django import forms

from .models import Med, Clients

class MedForm(forms.ModelForm):

    class Meta:
        model = Med
        fields = ['client', 'service', 'text', ]
        widgets = {
            'client': autocomplete.ModelSelect2(url='med-autocomplete', attrs={'class' : 'form-control'}),
            'service': autocomplete.ModelSelect2(url='service-autocomplete', attrs={'class' : 'form-control'}),
            'text': forms.Textarea(attrs={'class' : 'form-control'})
        }

med/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.utils import timezone
from django.db.models import Sum
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Med, Clients, Services
from .forms import MedForm
from dal import autocomplete


class MedAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Clients.objects.none()
        qs = Clients.objects.all()
        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs

class ServiceAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Services.objects.none()
        qs = Services.objects.all()
        if self.q:
            qs = qs.filter(title__istartswith=self.q)

        return qs

@login_required
def med_list(request):
    context = {}
    meds = Med.objects.filter(author=request.user).order_by('-published_date')
    current_page = Paginator(meds, 3)
    page = request.GET.get('page')
    try:
        context['med_list'] = current_page.page(page)
    except PageNotAnInteger:
        context['med_list'] = current_page.page(1)
    except EmptyPage:
        context['med_list'] = current_page.page(current_page.num_pages)
    return render(request, 'med/med_list.html', context)

@login_required
def med_new(request):
    if request.method == "POST":
        form = MedForm(request.POST)
        if form.is_valid():
            med = form.save(commit=False)
            med.author = request.user
            med.published_date = timezone.now()
            med.save()
            return redirect('med_list')
    else:
        form = MedForm()
    return render(request, 'med/med_edit.html', {'form': form})

@login_required
def med_edit(request, pk):
    med = get_object_or_404(Med, pk=pk)
    if request.method == "POST":
        form = MedForm(request.POST, instance=med)
        if form.is_valid():
            med = form.save(commit=False)
            med.author = request.user
            med.published_date = timezone.now()
            med.save()
            return redirect('med_list', pk=med.pk)
    else:
        form = MedForm(instance=med)
    return render(request, 'med/med_edit.html', {'form': form})

@login_required
def med_delete(request, pk):
    try:
        med = Med.objects.get(pk=pk)
        med.delete()
        return redirect('med_list')
    except Med.DoesNotExist:
        return redirect('med_list')

@login_required
def med_report(request):
    meds_day = Med.objects.filter(published_date__range=[timezone.now() - timezone.timedelta(1), timezone.now()])
    total_day = Med.objects.filter(
        published_date__range=[timezone.now() - timezone.timedelta(1), timezone.now()]).aggregate(
        total_d=Sum('service__price'))
    total_c_day = Med.objects.filter(
        published_date__range=[timezone.now() - timezone.timedelta(1), timezone.now()]).count()
    meds_week = Med.objects.filter(published_date__range=[timezone.now() - timezone.timedelta(7), timezone.now()])
    total_week = Med.objects.filter(
        published_date__range=[timezone.now() - timezone.timedelta(7), timezone.now()]).aggregate(
        total_d=Sum('service__price'))
    total_c_week = Med.objects.filter(
        published_date__range=[timezone.now() - timezone.timedelta(7), timezone.now()]).count()
    meds_mounth = Med.objects.filter(published_date__range=[timezone.now() - timezone.timedelta(30), timezone.now()])
    total_mounth = Med.objects.filter(
        published_date__range=[timezone.now() - timezone.timedelta(30), timezone.now()]).aggregate(
        total_d=Sum('service__price'))
    total_c_mounth = Med.objects.filter(
        published_date__range=[timezone.now() - timezone.timedelta(30), timezone.now()]).count()
    return render(request, 'med/med_report.html', {'meds_day': meds_day,
                                                   'total_c_day': total_c_day,
                                                   'total_day': total_day,
                                                   'meds_week': meds_week,
                                                   'total_c_week': total_c_week,
                                                   'total_week': total_week,
                                                   'meds_mounth': meds_mounth,
                                                   'total_c_mounth': total_c_mounth,
                                                   'total_mounth': total_mounth})

med/templates/med/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>МедЦентр</title>

    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" href="{% static 'css/med.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/22.ico' %}"/>
    <script src="https://kit.fontawesome.com/31aa44e023.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#"><img src="{% static 'img/22.svg' %}" class="nav-ico">МедЦентр</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'med_list' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clients:client_list' %}">Пациенты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'services:service_list' %}">Услуги</a>
                </li>
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'med_report' %}">Отчеты</a>
                    </li>
                {% endif %}
            </ul>
            <form class="form-inline my-2 my-lg-0">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="#">Врач: {{ user.get_full_name }}</a>
                    <a class="btn btn-secondary my-2 my-sm-0" href="{% url 'logout'%}?next={{request.path}}">Выйти</a>
                {% else %}
                    <a class="btn btn-secondary my-2 my-sm-0"  href="{% url 'login'%}?next={{request.path}}">Войти</a>
                {% endif %}
            </form>
        </div>
    </nav>

    <main role="main" class="container">
        {% block content %}
        {% endblock %}
    </main>

<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

med/templates/med/med_edit.html
{% extends 'med/base.html' %}

{% block content %}
    <h1>Добавить оказанную услугу</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.client.errors }}
                <lable for="{{ form.client.id_for_label }}">Пациент: </lable>
            {{ form.client }}
        </div>
        <div class="form-group">
           {{ form.service.errors }}
                <lable for="{{ form.service.id_for_label }}">Услуга: </lable>
           {{ form.service }}
        </div>
        <div class="form-group">
            {{ form.text.errors }}
                <lable for="{{ form.text.id_for_label }}">Описание: </lable>
            {{ form.text }}
        </div>
        {{ form.media }}
        <button type="submit" class="save btn btn-success">Сохранить</button>
    </form>
{% endblock %}

med/templates/med/med_list.html
{% extends 'med/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <h2 class="main-header">Оказанные услуги
        {% if user.is_authenticated %}
            <a href="{% url 'med_new' %}" class="top-menu btn btn-outline-primary btn-sm">Добавить <span class="far fa-plus-square"></span></a>
        {% endif %}
    </h2>
    {% bootstrap_pagination med_list %}
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <tbody>
                {% for med in med_list %}
                    <tr>
                        <td>
                            <div class="container">
                                <div class="row">
                                    <div class="col-sm-11 pre-inf">
                                        <b>Врач: </b><a href="#">{{ med.author.get_full_name }}</a>
                                        <pre class="pub_date"> - {{ med.published_date }}</pre>
                                    </div>
                                    <div class="col-sm-1 settin">
                                        <a class="btn-sm btn-default" href="{% url 'med_edit' pk=med.pk %}"><span class="far fa-edit"></span></a>
                                        <a class="btn-sm btn-default" href="{% url 'med_delete' pk=med.pk %}"><span class="far fa-trash-alt"></span></a>
                                    </div>
                                </div>

                                <h3><a href="{% url 'services:service_detail' pk=med.service.pk %}">{{ med.service.title }}</a> -- {{ med.service.price }} руб.</h3>

                                <p><b>Пациент: </b><a href="{% url 'clients:client_detail' pk=med.service.pk %}">{{ med.client.name }} {{ med.client.fam }}</a></p>
                                <p><b>Примечания: </b><br>{{ med.text|linebreaksbr }}</p>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% bootstrap_pagination med_list %}
    </div>
{% endblock %}

med/templates/med/med_report.html
{% extends 'med/base.html' %}

{% block breadcrumbs %}
    <div class="breadcrumb"><a href="{% url 'med_list' %}">Каталог статей</a></div>
{% endblock %}

{% block content %}
{% if user.is_superuser %}
    <div id="accordion">
      <div class="card">
        <div class="card-header" id="headingOne">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
              <h4>Отчет за текущий день</h4>
            </button>
          </h5>
        </div>

        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
          <div class="card-body">
            <h4><b>Оказано услуг: {{ total_c_day }} Итого: {{ total_day.total_d }}</b></h4>
              {% for med in meds_day %}
                    <tr>
                        <td>
                            <div class="block">
                                <a class="btn btn-default" href="{% url 'med_edit' pk=med.pk %}"><span class="far fa-edit"></span></a>
                                <a class="btn btn-default" href="{% url 'med_delete' pk=med.pk %}"><span class="far fa-trash-alt"></span></a>
                                <h3><a href="{% url 'services:service_detail' pk=med.service.pk %}">{{ med.service.title }}</a> -- {{ med.service.price }} руб.</h3>
                                <p><b>Врач: </b><a href="#">{{ med.author.get_full_name }}</a></p>
                                <p><b>Пациент: </b><a href="{% url 'clients:client_detail' pk=med.service.pk %}">{{ med.client.name }} {{ med.client.fam }}</a></p>
                                <pre><b>Дата визита: </b> {{ med.published_date }}</pre>
                                <p><b>Примечания: </b><br>{{ med.text|linebreaksbr }}</p>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingTwo">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              <h4>Отчет за последние 7 дней</h4>
            </button>
          </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
          <div class="card-body">
            <h4><b>Оказано услуг: {{ total_c_week }} Итого: {{ total_week.total_d }}</b></h4>
              {% for med in meds_week %}
                    <tr>
                        <td>
                            <div class="block">
                                <a class="btn btn-default" href="{% url 'med_edit' pk=med.pk %}"><span class="far fa-edit"></span></a>
                                <a class="btn btn-default" href="{% url 'med_delete' pk=med.pk %}"><span class="far fa-trash-alt"></span></a>
                                <h3><a href="{% url 'services:service_detail' pk=med.service.pk %}">{{ med.service.title }}</a> -- {{ med.service.price }} руб.</h3>
                                <p><b>Врач: </b><a href="#">{{ med.author.get_full_name }}</a></p>
                                <p><b>Пациент: </b><a href="{% url 'clients:client_detail' pk=med.service.pk %}">{{ med.client.name }} {{ med.client.fam }}</a></p>
                                <pre><b>Дата визита: </b> {{ med.published_date }}</pre>
                                <p><b>Примечания: </b><br>{{ med.text|linebreaksbr }}</p>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingThree">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              <h4>Отчет за месяц</h4>
            </button>
          </h5>
        </div>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
          <div class="card-body">
            <h4><b>Оказано услуг: {{ total_c_mounth }} Итого: {{ total_mounth.total_d }} руб.</b></h4>
              {% for med in meds_mounth %}
                    <tr>
                        <td>
                            <div class="block">
                                <a class="btn btn-default" href="{% url 'med_edit' pk=med.pk %}"><span class="far fa-edit"></span></a>
                                <a class="btn btn-default" href="{% url 'med_delete' pk=med.pk %}"><span class="far fa-trash-alt"></span></a>
                                <h3><a href="{% url 'services:service_detail' pk=med.service.pk %}">{{ med.service.title }}</a> -- {{ med.service.price }} руб.</h3>
                                <p><b>Врач: </b><a href="#">{{ med.author.get_full_name }}</a></p>
                                <p><b>Пациент: </b><a href="{% url 'clients:client_detail' pk=med.service.pk %}">{{ med.client.name }} {{ med.client.fam }}</a></p>
                                <pre><b>Дата визита: </b> {{ med.published_date }}</pre>
                                <p><b>Примечания: </b><br>{{ med.text|linebreaksbr }}</p>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
          </div>
        </div>
      </div>
    </div>
{% else %}
    <p class="alert alert-warning" role="alert">У вашей учетной записи нет доступа к содержимому этой страницы. Для получения доступа зайдите под другой учетной записью.</p>
{% endif %}
{% endblock %}