clients/urls.py
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('clients', views.client_list, name='client_list'),
    path('clients/<int:pk>/', views.client_detail, name='client_detail'),
    path('clients/new/', views.client_new, name='client_new'),
    path('clients/<int:pk>/edit/', views.client_edit, name='client_edit'),
    path('clients/<int:pk>/delete/', views.client_delete, name='client_delete'),
]

med/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from .models import Clients
from med.views import MedAutocomplete, ServiceAutocomplete

urlpatterns = [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    path('', views.med_list, name='med_list'),
    path('report', views.med_report, name='med_report'),
    path('med/new/', views.med_new, name='med_new'),
    path('med/<int:pk>/edit/', views.med_edit, name='med_edit'),
    path('med/<int:pk>/delete/', views.med_delete, name='med_delete'),
    url(r'^med-autocomplete/$', MedAutocomplete.as_view(), name='med-autocomplete'),
    url(r'^service-autocomplete/$', ServiceAutocomplete.as_view(), name='service-autocomplete'),
]

medecine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('med.urls')),
    path('', include('clients.urls')),
    path('', include('services.urls')),
]

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('services', views.service_list, name='service_list'),
    path('services/<int:pk>/', views.service_detail, name='service_detail'),
    path('services/new/', views.service_new, name='service_new'),
    path('services/<int:pk>/edit/', views.service_edit, name='service_edit'),
    path('services/<int:pk>/delete/', views.service_delete, name='service_delete'),
]

clients/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Clients(models.Model):
    name = models.CharField(max_length=200)
    fam = models.CharField(max_length=200)
    date_birthday = models.DateField()
    med_card = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.name

clients/forms.py
from django import forms
import datetime
from .models import Clients

class ClientsForm(forms.ModelForm):

    class Meta:
        model = Clients
        fields = ['name', 'fam', 'date_birthday', 'med_card',]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'fam': forms.TextInput(attrs={'class': 'form-control'}),
            'date_birthday': forms.DateInput(format='%d/%m/%Y', attrs={'class': 'form-control'}),
            'med_card': forms.Textarea(attrs={'class': 'form-control'}),
        }

clients/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.utils import timezone
from .models import Clients
from med.models import Med
from .forms import ClientsForm

@login_required
def client_list(request):
    context = {}
    clients = Clients.objects.all().order_by('-published_date')
    current_page = Paginator(clients, 10)
    page = request.GET.get('page')
    try:
        context['client_list'] = current_page.page(page)
    except PageNotAnInteger:
        context['client_list'] = current_page.page(1)
    except EmptyPage:
        context['client_list'] = current_page.page(current_page.num_pages)
    return render(request, 'clients/client_list.html', context)

@login_required
def client_detail(request, pk):
    context = {}
    client = get_object_or_404(Clients, pk=pk)
    try:
        med = Med.objects.filter(client=pk).latest('published_date')
    except:
        med = 'Null'
    meds = Med.objects.filter(client=pk).order_by('-published_date')
    current_page = Paginator(meds, 3)
    page = request.GET.get('page')
    try:
        context['med_list'] = current_page.page(page)
    except PageNotAnInteger:
        context['med_list'] = current_page.page(1)
    except EmptyPage:
        context['med_list'] = current_page.page(current_page.num_pages)
    return render(request, 'clients/client_detail.html', {'client': client,
                                                          'med_list': context['med_list'],
                                                          'med': med})

@login_required
def client_new(request):
    if request.method == "POST":
        form = ClientsForm(request.POST)
        if form.is_valid():
            clients = form.save(commit=False)
            clients.published_date = timezone.now()
            clients.save()
            return redirect('clients:client_list')
    else:
        form = ClientsForm()
    return render(request, 'clients/client_edit.html', {'form': form})

@login_required
def client_edit(request, pk):
    clients = get_object_or_404(Clients, pk=pk)
    if request.method == "POST":
        form = ClientsForm(request.POST, instance=clients)
        if form.is_valid():
            clients = form.save(commit=False)
            clients.published_date = timezone.now()
            clients.save()
            return redirect('clients:client_list')
    else:
        form = ClientsForm(instance=clients)
    return render(request, 'clients/client_edit.html', {'form': form})

@login_required
def client_delete(request, pk):
    try:
        clients = Clients.objects.get(pk=pk)
        clients.delete()
        return redirect('clients:client_list')
    except Clients.DoesNotExist:
        return redirect('clients:client_list')

clients/templates/clients/client_detail.html
{% extends 'med/base.html' %}
{% load bootstrap4 %}
{% block content %}
    <h2 class="main-header">{{ client.name }} {{ client.fam }}</h2>
    <p><b>Дата рождения:</b> {{ client.date_birthday }}</p>
    <p><b>Мед. карта:</b> <br><br> {{ client.med_card }}<br><br></p>
    <p><b>Дата последнего посещения:</b> {{ med.created_date|default:'Пациент еще не воспользовался услугами мед. центра!' }}</p>
    <br><br>

    <h3 class="main-header">Оказанные услуги</h3>
    {% bootstrap_pagination med_list %}
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <tbody>
                {% for med in med_list %}
                    <tr>
                        <td>
                            <div class="container">
                                <div class="row">
                                    <div class="col-sm-11 pre-inf">
                                        <b>Врач: </b><a href="#">{{ med.author.get_full_name }}</a>
                                        <pre class="pub_date"> - {{ med.published_date }}</pre>
                                    </div>
                                    <div class="col-sm-1 settin">
                                        <a class="btn-sm btn-default" href="{% url 'med_edit' pk=med.pk %}"><span class="far fa-edit"></span></a>
                                        <a class="btn-sm btn-default" href="{% url 'med_delete' pk=med.pk %}"><span class="far fa-trash-alt"></span></a>
                                    </div>
                                </div>

                                <h3><a href="{% url 'services:service_detail' pk=med.service.pk %}">{{ med.service.title }}</a> -- {{ med.service.price }} руб.</h3>

                                <p><b>Пациент: </b><a href="{% url 'clients:client_detail' pk=med.service.pk %}">{{ med.client.name }} {{ med.client.fam }}</a></p>
                                <p><b>Примечания: </b><br>{{ med.text|linebreaksbr }}</p>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% bootstrap_pagination med_list %}
    </div>
{% endblock %}

clients/templates/clients/client_edit.html
{% extends 'med/base.html' %}

{% block content %}
    <h1>Добавить пациента</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            <lable for="{{ form.name.id_for_label }}">Имя: </lable>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
        <div class="form-group">
            <lable for="{{ form.fam.id_for_label }}">Фамилия: </lable>
            {{ form.fam }}
            {{ form.fam.errors }}
        </div>
        <div class="form-group">
            <lable for="{{ form.date_birthday.id_for_label }}">Дата рождения: </lable>
            {{ form.date_birthday }}
            {{ form.date_birthday.errors }}
        </div>
        <div class="form-group">
            <lable for="{{ form.med_card.id_for_label }}">Мед. карта: </lable>
            {{ form.med_card }}
            {{ form.med_card.errors }}
        </div>
        {{ form.media }}
        <button type="submit" class="save btn btn-success">Сохранить</button>
    </form>
{% endblock %}

clients/templates/clients/client_list.html
{% extends 'med/base.html' %}
{% load bootstrap4 %}
{% block content %}
    <h2 class="main-header">Список пациентов
        {% if user.is_authenticated %}
            <a href="{% url 'clients:client_new' %}" class="top-menu btn btn-outline-primary btn-sm">Добавить <span class="far fa-plus-square"></span></a>
        {% endif %}
    </h2>
    {% bootstrap_pagination client_list %}
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <tbody>
                {% for client in client_list %}
                    <tr>
                        <td>
                            <div class="container">
                                <div class="row">
                                    <div class="col-sm-11"></div>
                                    <div class="col-sm-1 settin">
                                        <a class="btn-sm btn-default" href="{% url 'clients:client_edit' pk=client.pk %}"><span class="far fa-edit"></span></a>
                                        <a class="btn-sm btn-default" href="{% url 'clients:client_delete' pk=client.pk %}"><span class="far fa-trash-alt"></span></a>
                                    </div>
                                </div>
                            </div>
                            <h3><a href="{% url 'clients:client_detail' pk=client.pk %}">{{ client.name }} {{ client.fam }}</a></h3>
                            <pre><b>Дата рождения: </b> {{ client.date_birthday }}</pre>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% bootstrap_pagination client_list %}
    </div>
{% endblock %}