med/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from .models import Clients
from med.views import MedAutocomplete, ServiceAutocomplete

urlpatterns = [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    path('', views.med_list, name='med_list'),
    path('report', views.med_report, name='med_report'),
    path('med/new/', views.med_new, name='med_new'),
    path('med/<int:pk>/edit/', views.med_edit, name='med_edit'),
    path('med/<int:pk>/delete/', views.med_delete, name='med_delete'),
    url(r'^med-autocomplete/$', MedAutocomplete.as_view(), name='med-autocomplete'),
    url(r'^service-autocomplete/$', ServiceAutocomplete.as_view(), name='service-autocomplete'),
]

medecine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('med.urls')),
    path('', include('clients.urls')),
    path('', include('services.urls')),
]

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('services', views.service_list, name='service_list'),
    path('services/<int:pk>/', views.service_detail, name='service_detail'),
    path('services/new/', views.service_new, name='service_new'),
    path('services/<int:pk>/edit/', views.service_edit, name='service_edit'),
    path('services/<int:pk>/delete/', views.service_delete, name='service_delete'),
]

services/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Services(models.Model):
    title = models.CharField(max_length=200)
    price = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

services/forms.py
from django import forms

from .models import Services

class ServicesForm(forms.ModelForm):

    class Meta:
        model = Services
        fields = ['title', 'price', 'text',]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'})
        }

services/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.utils import timezone
from .models import Services
from .forms import ServicesForm

@login_required
def service_list(request):
    context = {}
    services = Services.objects.all()
    current_page = Paginator(services, 5)
    page = request.GET.get('page')
    try:
        context['service_list'] = current_page.page(page)
    except PageNotAnInteger:
        context['service_list'] = current_page.page(1)
    except EmptyPage:
        context['service_list'] = current_page.page(current_page.num_pages)
    return render(request, 'services/service_list.html', context)

@login_required
def service_detail(request, pk):
    service = get_object_or_404(Services, pk=pk)
    return render(request, 'services/service_detail.html', {'service': service})

@login_required
def service_new(request):
    if request.method == "POST":
        form = ServicesForm(request.POST)
        if form.is_valid():
            services = form.save(commit=False)
            services.published_date = timezone.now()
            services.save()
            return redirect('services:service_list')
    else:
        form = ServicesForm()
    return render(request, 'services/service_edit.html', {'form': form})

@login_required
def service_edit(request, pk):
    services = get_object_or_404(Services, pk=pk)
    if request.method == "POST":
        form = ServicesForm(request.POST, instance=services)
        if form.is_valid():
            services = form.save(commit=False)
            services.published_date = timezone.now()
            services.save()
            return redirect('services:service_list')
    else:
        form = ServicesForm(instance=services)
    return render(request, 'services/service_edit.html', {'form': form})

@login_required
def service_delete(request, pk):
    try:
        services = Services.objects.get(pk=pk)
        services.delete()
        return redirect('services:service_list')
    except Services.DoesNotExist:
        return redirect('services:service_list')

services/templates/services/service_detail.html
{% extends 'med/base.html' %}

{% block content %}
    <h2 class="main-header">{{ service.title }}</h2>
    <h3>Стоимость: {{ service.price }} руб.</h3><br>
    <p>Описание: <br><br>{{ service.text }}</p>

{% endblock %}

services/templates/services/service_edit.html
{% extends 'med/base.html' %}

{% block content %}
    <h1>Добавить новую услугу</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            <lable for="{{ form.title.id_for_label }}">Название: </lable>
            {{ form.title }}
            {{ form.title.errors }}
        </div>
        <div class="form-group">
            <lable for="{{ form.price.id_for_label }}">Стоимость: </lable>
            {{ form.price }}
            {{ form.price.errors }}
        </div>
        <div class="form-group">
            <lable for="{{ form.text.id_for_label }}">Описание: </lable>
            {{ form.text }}
            {{ form.text.errors }}
        </div>
        {{ form.media }}
        <button type="submit" class="save btn btn-success">Сохранить</button>
    </form>
{% endblock %}

services/templates/services/service_list.html
{% extends 'med/base.html' %}
{% load bootstrap4 %}
{% block content %}
    <h2 class="main-header">Список услуг
        {% if user.is_authenticated %}
            <a href="{% url 'services:service_new' %}" class="top-menu btn btn-outline-primary btn-sm">Добавить <span class="far fa-plus-square"></span></a>
        {% endif %}
    </h2>
    {% bootstrap_pagination service_list %}
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <tbody>
                {% for service in service_list %}
                    <tr>
                        <td>
                            <div class="block">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-sm-11"></div>
                                        <div class="col-sm-1 settin">
                                            <a class="btn-sm btn-default" href="{% url 'services:service_edit' pk=service.pk %}"><span class="far fa-edit"></span></a>
                                            <a class="btn-sm btn-default" href="{% url 'services:service_delete' pk=service.pk %}"><span class="far fa-trash-alt"></span></a>
                                        </div>
                                    </div>
                                </div>
                                <h3><a href="{% url 'services:service_detail' pk=service.pk %}">{{ service.title }}</a></h3>
                                <p>Стоимость услуги: {{ service.price }} руб.</p>
                                <p>Описание услуги:<br> {{ service.text }}</p>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% bootstrap_pagination service_list %}
    </div>
{% endblock %}